# Generated by Django 6.0.7 on 2026-07-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='github_link',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='live_link',
            new_name='live_demo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(default='7th Semester', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='cgpa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
